### ISSUE TITLE
Support collections

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-requirements-updater#1]
It's bad enough this playbook can wreck a role requirements file. Let's make it so it can handle a list of collections, too.

Example `requirements.yml` that is currently slashed in half by this playbook:

```yaml
---
roles:
  # Install a role from Ansible Galaxy.
  - src: geerlingguy.java
    version: 1.9.6

collections:
  # Install a collection from Ansible Galaxy.
  - name: geerlingguy.php_roles
    version: 0.9.3
    source: https://galaxy.ansible.com
```

[Straight from the docs](https://docs.ansible.com/ansible/latest/user_guide/collections_using.html#install-multiple-collections-with-a-requirements-file).
