### ISSUE TITLE
Add example of requirements.yml file with proper formatting in README

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-requirements-updater#4]
I just tried updating ye olde requirements file like the following:

```yaml
---
- src: geerlingguy.ansible
  version: 1.2.0
- src: geerlingguy.certbot
  version: 3.0.0
- src: geerlingguy.docker
  version: 2.1.0
```

And that didn't work, because this playbook expects a more modern style, like:

```yaml
---
roles:
  - name: geerlingguy.ansible
    version: 1.2.0
  - name: geerlingguy.certbot
    version: 3.0.0
  - name: geerlingguy.docker
    version: 2.1.0
```
